### ISSUE TITLE
Create a function to create new *.Vester.ps1 test files.

### ISSUE THREAD

**Issue by jpsider** [WahlNetwork/Vester#181] opened 2017-09-24 19:42 UTC
## Expected Behavior
This file should accept an Object as a parameter, and use that to build *.Vester.ps1 files. This will allow users to quickly build test files for new settings. There of course is an assumption that each item in the object could be gathered and fixed in the same way.

## Current Behavior
Currently users need to manually create the test files.

## Possible Solution
I'll check in my first pass. I think that a parameter for "command" will need to be added, as the current solution is hardcoded with "Get-AdvancedSetting -Entity ......". Also, better handling of special characters being returned by PowerCLI in the setting names.

## Steps to Reproduce (for bugs)
n/a

## Context
This quick script allowed me to create a list of 600+ advanced settings for vCenter in seconds. I think for some users thats too much, and they may not care about all of those. But it's a nice feature to have available if you need to compare every detail about two separate Items in your environment.

## Your Environment
* Vester module version used: 1.2.0 
* PowerCLI version: 6.5.2.6
* Pester version: 4.0.5
* Operating System and PowerShell version: Win10, PS5 build 15063, Rev 608

**Comment by brianbunke** [comment] 2017-09-26 04:22
I'm reading this as (mostly?) a duplicate of #102, and if so, I'd prefer to consolidate the discussion.

If you feel like this is separate, please feel free to reopen and clarify.

**Closed by brianbunke** 2017-09-26 04:22 UTC
Labels: duplicate
